---
apiVersion: v1
kind: Secret
metadata:
  name: donschenck-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/donschenck-gateway-gitops
